// <auto-generated />
namespace BhuInfo.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class NewsCategoryDataContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewsCategoryDataContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201609022203332_NewsCategoryDataContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
